/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	browserv1 "github.com/alcounit/browser-controller/apis/browser/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BrowserLister helps list Browsers.
// All objects returned here must be treated as read-only.
type BrowserLister interface {
	// List lists all Browsers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*browserv1.Browser, err error)
	// Browsers returns an object that can list and get Browsers.
	Browsers(namespace string) BrowserNamespaceLister
	BrowserListerExpansion
}

// browserLister implements the BrowserLister interface.
type browserLister struct {
	listers.ResourceIndexer[*browserv1.Browser]
}

// NewBrowserLister returns a new BrowserLister.
func NewBrowserLister(indexer cache.Indexer) BrowserLister {
	return &browserLister{listers.New[*browserv1.Browser](indexer, browserv1.Resource("browser"))}
}

// Browsers returns an object that can list and get Browsers.
func (s *browserLister) Browsers(namespace string) BrowserNamespaceLister {
	return browserNamespaceLister{listers.NewNamespaced[*browserv1.Browser](s.ResourceIndexer, namespace)}
}

// BrowserNamespaceLister helps list and get Browsers.
// All objects returned here must be treated as read-only.
type BrowserNamespaceLister interface {
	// List lists all Browsers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*browserv1.Browser, err error)
	// Get retrieves the Browser from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*browserv1.Browser, error)
	BrowserNamespaceListerExpansion
}

// browserNamespaceLister implements the BrowserNamespaceLister
// interface.
type browserNamespaceLister struct {
	listers.ResourceIndexer[*browserv1.Browser]
}
