/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisbrowserv1 "github.com/alcounit/browser-controller/apis/browser/v1"
	clientset "github.com/alcounit/browser-controller/pkg/clientset"
	internalinterfaces "github.com/alcounit/browser-controller/pkg/informers/externalversions/internalinterfaces"
	browserv1 "github.com/alcounit/browser-controller/pkg/listers/browser/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BrowserInformer provides access to a shared informer and lister for
// Browsers.
type BrowserInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() browserv1.BrowserLister
}

type browserInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBrowserInformer constructs a new informer for Browser type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBrowserInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBrowserInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBrowserInformer constructs a new informer for Browser type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBrowserInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SelenosisV1().Browsers(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SelenosisV1().Browsers(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SelenosisV1().Browsers(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SelenosisV1().Browsers(namespace).Watch(ctx, options)
			},
		},
		&apisbrowserv1.Browser{},
		resyncPeriod,
		indexers,
	)
}

func (f *browserInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBrowserInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *browserInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisbrowserv1.Browser{}, f.defaultInformer)
}

func (f *browserInformer) Lister() browserv1.BrowserLister {
	return browserv1.NewBrowserLister(f.Informer().GetIndexer())
}
