---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: browser-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - browser.selenosis.io
  resources:
  - browsers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - browser.selenosis.io
  resources:
  - browsers/finalizers
  verbs:
  - update
- apiGroups:
  - browser.selenosis.io
  resources:
  - browsers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - browserconfig.selenosis.io
  resources:
  - browserconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - browserconfig.selenosis.io
  resources:
  - browserconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - browserconfig.selenosis.io
  resources:
  - browserconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
