/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	browserconfigv1 "github.com/alcounit/browser-controller/apis/browserconfig/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BrowserConfigLister helps list BrowserConfigs.
// All objects returned here must be treated as read-only.
type BrowserConfigLister interface {
	// List lists all BrowserConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*browserconfigv1.BrowserConfig, err error)
	// BrowserConfigs returns an object that can list and get BrowserConfigs.
	BrowserConfigs(namespace string) BrowserConfigNamespaceLister
	BrowserConfigListerExpansion
}

// browserConfigLister implements the BrowserConfigLister interface.
type browserConfigLister struct {
	listers.ResourceIndexer[*browserconfigv1.BrowserConfig]
}

// NewBrowserConfigLister returns a new BrowserConfigLister.
func NewBrowserConfigLister(indexer cache.Indexer) BrowserConfigLister {
	return &browserConfigLister{listers.New[*browserconfigv1.BrowserConfig](indexer, browserconfigv1.Resource("browserconfig"))}
}

// BrowserConfigs returns an object that can list and get BrowserConfigs.
func (s *browserConfigLister) BrowserConfigs(namespace string) BrowserConfigNamespaceLister {
	return browserConfigNamespaceLister{listers.NewNamespaced[*browserconfigv1.BrowserConfig](s.ResourceIndexer, namespace)}
}

// BrowserConfigNamespaceLister helps list and get BrowserConfigs.
// All objects returned here must be treated as read-only.
type BrowserConfigNamespaceLister interface {
	// List lists all BrowserConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*browserconfigv1.BrowserConfig, err error)
	// Get retrieves the BrowserConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*browserconfigv1.BrowserConfig, error)
	BrowserConfigNamespaceListerExpansion
}

// browserConfigNamespaceLister implements the BrowserConfigNamespaceLister
// interface.
type browserConfigNamespaceLister struct {
	listers.ResourceIndexer[*browserconfigv1.BrowserConfig]
}
