/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	browserconfigv1 "github.com/alcounit/browser-controller/apis/browserconfig/v1"
	scheme "github.com/alcounit/browser-controller/pkg/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BrowserConfigsGetter has a method to return a BrowserConfigInterface.
// A group's client should implement this interface.
type BrowserConfigsGetter interface {
	BrowserConfigs(namespace string) BrowserConfigInterface
}

// BrowserConfigInterface has methods to work with BrowserConfig resources.
type BrowserConfigInterface interface {
	Create(ctx context.Context, browserConfig *browserconfigv1.BrowserConfig, opts metav1.CreateOptions) (*browserconfigv1.BrowserConfig, error)
	Update(ctx context.Context, browserConfig *browserconfigv1.BrowserConfig, opts metav1.UpdateOptions) (*browserconfigv1.BrowserConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, browserConfig *browserconfigv1.BrowserConfig, opts metav1.UpdateOptions) (*browserconfigv1.BrowserConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*browserconfigv1.BrowserConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*browserconfigv1.BrowserConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *browserconfigv1.BrowserConfig, err error)
	BrowserConfigExpansion
}

// browserConfigs implements BrowserConfigInterface
type browserConfigs struct {
	*gentype.ClientWithList[*browserconfigv1.BrowserConfig, *browserconfigv1.BrowserConfigList]
}

// newBrowserConfigs returns a BrowserConfigs
func newBrowserConfigs(c *BrowserconfigV1Client, namespace string) *browserConfigs {
	return &browserConfigs{
		gentype.NewClientWithList[*browserconfigv1.BrowserConfig, *browserconfigv1.BrowserConfigList](
			"browserconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *browserconfigv1.BrowserConfig { return &browserconfigv1.BrowserConfig{} },
			func() *browserconfigv1.BrowserConfigList { return &browserconfigv1.BrowserConfigList{} },
		),
	}
}
