/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	browserv1 "github.com/alcounit/browser-controller/apis/browser/v1"
	scheme "github.com/alcounit/browser-controller/pkg/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BrowsersGetter has a method to return a BrowserInterface.
// A group's client should implement this interface.
type BrowsersGetter interface {
	Browsers(namespace string) BrowserInterface
}

// BrowserInterface has methods to work with Browser resources.
type BrowserInterface interface {
	Create(ctx context.Context, browser *browserv1.Browser, opts metav1.CreateOptions) (*browserv1.Browser, error)
	Update(ctx context.Context, browser *browserv1.Browser, opts metav1.UpdateOptions) (*browserv1.Browser, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, browser *browserv1.Browser, opts metav1.UpdateOptions) (*browserv1.Browser, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*browserv1.Browser, error)
	List(ctx context.Context, opts metav1.ListOptions) (*browserv1.BrowserList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *browserv1.Browser, err error)
	BrowserExpansion
}

// browsers implements BrowserInterface
type browsers struct {
	*gentype.ClientWithList[*browserv1.Browser, *browserv1.BrowserList]
}

// newBrowsers returns a Browsers
func newBrowsers(c *SelenosisV1Client, namespace string) *browsers {
	return &browsers{
		gentype.NewClientWithList[*browserv1.Browser, *browserv1.BrowserList](
			"browsers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *browserv1.Browser { return &browserv1.Browser{} },
			func() *browserv1.BrowserList { return &browserv1.BrowserList{} },
		),
	}
}
